<!doctype html>
<html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"><meta><title>基于ObjectARX .NET的AutoCAD二次开发：项目配置 - uint128&#039;s Blog</title><link rel="manifest" href="/manifest.json"><meta name="application-name" content="uint128&#039;s Blog"><meta name="msapplication-TileImage" content="/favicon.ico"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="uint128&#039;s Blog"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="description" content="ObjectARX 是 AutoCAD 的开发环境，提供面向对象的 C++ 以及 .NET 编程接口。本文将介绍两种配置 Visual Studio 项目的方法，包括不使用 Wizard 的方法。"><meta property="og:type" content="blog"><meta property="og:title" content="基于ObjectARX .NET的AutoCAD二次开发：项目配置"><meta property="og:url" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/"><meta property="og:site_name" content="uint128&#039;s Blog"><meta property="og:description" content="ObjectARX 是 AutoCAD 的开发环境，提供面向对象的 C++ 以及 .NET 编程接口。本文将介绍两种配置 Visual Studio 项目的方法，包括不使用 Wizard 的方法。"><meta property="og:locale" content="zh_CN"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/wizard_1.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/wizard_2.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/wizard_3.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_1.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_2.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_3.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_4.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_nuget_1.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_nuget_2.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_debug_1.png"><meta property="og:image" content="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_debug_2.png"><meta property="article:published_time" content="2023-07-11T06:30:05.000Z"><meta property="article:modified_time" content="2023-07-11T17:29:25.019Z"><meta property="article:author" content="uint128.com"><meta property="article:tag" content="AutoCAD"><meta property="article:tag" content="CSharp"><meta property="twitter:card" content="summary"><meta property="twitter:image" content="./wizard_1.png"><script type="application/ld+json">{"@context":"https://schema.org","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/"},"headline":"uint128's Blog","image":["https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/wizard_1.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/wizard_2.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/wizard_3.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_1.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_2.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_3.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_4.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_nuget_1.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_nuget_2.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_debug_1.png","https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/manual_debug_2.png"],"datePublished":"2023-07-11T06:30:05.000Z","dateModified":"2023-07-11T17:29:25.019Z","author":{"@type":"Person","name":"uint128.com"},"publisher":{"@type":"Organization","logo":{"@type":"ImageObject"}},"description":"ObjectARX 是 AutoCAD 的开发环境，提供面向对象的 C++ 以及 .NET 编程接口。本文将介绍两种配置 Visual Studio 项目的方法，包括不使用 Wizard 的方法。"}</script><link rel="canonical" href="https://uint128.com/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/"><link rel="alternate" href="/atom.xml" title="uint128&#039;s Blog" type="application/atom+xml"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@9.12.0/styles/atom-one-light.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;600&amp;family=Source+Code+Pro"><link rel="stylesheet" href="/css/default.css"><style>body>.footer,body>.navbar,body>.section{opacity:0}</style><!--!--><!--!--><!--!--><!--!--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/css/lightgallery.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css"><!--!--><!--!--><!--!--><style>.pace{-webkit-pointer-events:none;pointer-events:none;-webkit-user-select:none;-moz-user-select:none;user-select:none}.pace-inactive{display:none}.pace .pace-progress{background:#3273dc;position:fixed;z-index:2000;top:0;right:100%;width:100%;height:2px}</style><script src="https://cdn.jsdelivr.net/npm/pace-js@1.2.4/pace.min.js"></script><!--!--><!--!--><!-- hexo injector head_end start -->
<!-- hexo-inject:begin --><!-- hexo-inject:end --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css">
<!-- hexo injector head_end end --><meta name="generator" content="Hexo 6.2.0"><!-- hexo-inject:begin --><!-- hexo-inject:end --></head><body class="is-2-column"><script type="text/javascript" src="/js/imaegoo/night.js"></script><canvas id="universe"></canvas><nav class="navbar navbar-main"><div class="container"><div class="navbar-brand justify-content-center"><a class="navbar-item navbar-logo" href="/">uint128&#039;s Blog</a></div><div class="navbar-menu"><div class="navbar-start"><a class="navbar-item" href="/">Home</a><a class="navbar-item" href="/archives">Archives</a><a class="navbar-item" href="/tags">Tags</a><a class="navbar-item" href="/about">About</a></div><div class="navbar-end"><a class="navbar-item" target="_blank" rel="noopener" title="My GitHub" href="https://github.com/cyanray"><i class="fab fa-github"></i></a><a class="navbar-item" target="_blank" rel="noopener" title="RSS" href="/atom.xml"><i class="fas fa-rss"></i></a><a class="navbar-item is-hidden-tablet catalogue" title="目录" href="javascript:;"><i class="fas fa-list-ul"></i></a><a class="navbar-item night" id="night-nav" title="Night Mode" href="javascript:;"><i class="fas fa-moon" id="night-icon"></i></a><a class="navbar-item search" title="搜索" href="javascript:;"><i class="fas fa-search"></i></a></div></div></div></nav><section class="section"><div class="container"><div class="columns"><div class="column order-2 column-main is-8-tablet is-8-desktop is-8-widescreen"><div class="card"><article class="card-content article" role="article"><div class="article-meta is-size-7 is-uppercase level is-mobile"><div class="level-left"><span class="level-item"><time dateTime="2023-07-11T06:30:05.000Z" title="2023/7/11 14:30:05">2023-07-11</time>发表</span><span class="level-item"><time dateTime="2023-07-11T17:29:25.019Z" title="2023/7/12 01:29:25">2023-07-12</time>更新</span></div></div><h1 class="title is-3 is-size-4-mobile">基于ObjectARX .NET的AutoCAD二次开发：项目配置</h1><div class="content"><p>ObjectARX 是 AutoCAD 的开发环境，提供面向对象的 C++ 以及 .NET 编程接口。本文将介绍两种配置 Visual Studio 项目的方法，包括不使用 Wizard 的方法。<br><span id="more"></span></p>
<!-- hexo-inject:begin --><!-- hexo-inject:end --><h2 id="🔗开发目标"><a href="#🔗开发目标" class="headerlink" title="🔗开发目标"></a>🔗开发目标</h2><p>在基于 ObjectARX .NET API的 AutoCAD 二次开发中，最终需要得到的是一个（或若干个） <strong>.dll 文件</strong>。在 AutoCAD 中使用 <strong>NETLOAD</strong> 指令加载这个 <strong>.dll</strong> 文件，就可以导入包含在其中的 <strong>指令</strong>，从而扩展 AutoCAD 的功能。这些指令具体做什么工作都是自己编写代码实现的，名字也是自己取的，使用的时候和执行 AutoCAD 的内置指令没有区别。</p>
<p>如果你有一定的 C# 语言的程序开发基础，那么你应该已经联想到你需要一个类型为 <strong>类库</strong>(class library) 的项目，因为它的编译产物正是 <strong>.dll</strong> 文件。下文中我会介绍两种创建这个项目的方法：一种是基于 <strong>AutoCAD DotNet Wizard</strong> 的向导式创建方法，这个向导会询问你 ObjectARX 与 AutoCAD 的安装位置，自动完成项目的<strong>依赖引用</strong>与<strong>调试</strong>设置；另一种是创建普通的类库项目，然后通过 Nuget 或手动编辑的方式完成<strong>依赖引用</strong>的设置。</p>
<h2 id="🔗前期准备"><a href="#🔗前期准备" class="headerlink" title="🔗前期准备"></a>🔗前期准备</h2><h3 id="📖安装-Visual-Studio"><a href="#📖安装-Visual-Studio" class="headerlink" title="📖安装 Visual Studio"></a>📖安装 Visual Studio</h3><p>网上教程很多，这里不再介绍，注意你只需要在 Visual Studio Installer 里勾选 <strong>.NET 桌面开发</strong> 即可。</p>
<blockquote>
<p>Visual Studio Installer 从 Visual Studio 2019 版本开始有（如果我没记错的话），更旧的版本应该是默认安装 .NET 桌面开发的。</p>
</blockquote>
<p>我个人是推荐采用最新版本的 Visual Studio。虽然这可能会导致你无法使用 AutoCAD DotNet Wizard，因为它同时要求了 Visual Studio 与 AutoCAD 的版本。比如 AutoCAD 2023 DotNet Wizard，要求 AutoCAD 2023 以及 Visual Studio 2019。如果你使用的是早期的 AutoCAD 版本，可能会同时要求你使用非常古老的 Visual Studio，这非常的不推荐。</p>
<p>下文会介绍不使用 AutoCAD DotNet Wizard 的方法，采用此方法可以不考虑 Visual Studio 的版本，请直接安装最新版本，以获得最佳的开发体验。</p>
<h3 id="📖下载并解压-ObjectARX"><a href="#📖下载并解压-ObjectARX" class="headerlink" title="📖下载并解压 ObjectARX"></a>📖下载并解压 ObjectARX</h3><p>请根据你的操作系统（Windows Or Mac）以及电脑上的 AutoCAD 版本，在这个链接 <a target="_blank" rel="noopener" href="https://www.autodesk.com/developer-network/platform-technologies/autocad/objectarx-download">https://www.autodesk.com/developer-network/platform-technologies/autocad/objectarx-download</a> 里下载 ObjectARX。</p>
<blockquote>
<p>这个页面在搜索引擎中可能搜索不到，因为它是填写了邮箱之后跳转而来的。</p>
</blockquote>
<p>ObjectARX 没有安装过程，下载好之后运行会提示需要解压，解压得到的目录就是 ObjectARX 本身，这个目录的名字类似于： <strong>ObjectARX_for_AutoCAD_2024_Win_64bit_dlm</strong>。</p>
<h3 id="📖下载并安装-AutoCAD-DotNet-Wizard（可选）"><a href="#📖下载并安装-AutoCAD-DotNet-Wizard（可选）" class="headerlink" title="📖下载并安装 AutoCAD DotNet Wizard（可选）"></a>📖下载并安装 AutoCAD DotNet Wizard（可选）</h3><p>Wizard 可以在链接 <a target="_blank" rel="noopener" href="https://www.autodesk.com/developer-network/platform-technologies/autocad">https://www.autodesk.com/developer-network/platform-technologies/autocad</a> 的<strong>最下面</strong>，Tools 一栏里找到。（请下载 <strong>AutoCAD DotNet Wizard</strong> 而不是 AutoCAD Wizard）</p>
<p>上面提到 AutoCAD DotNet Wizard 同时要求了 Visual Studio 与 AutoCAD 的版本，但其实安装程序只会检测你电脑上所安装的 Visual Studio 是否满足版本要求，因此可以只根据 Visual Studio 的版本来选择 Wizard 的版本。比如 Wizard 2024 要求 Visual Studio 2022，Wizard 2023 要求 Visual Studio 2019（有一个对应关系，可以逐个版本下载，看看哪个能装上）。</p>
<h2 id="🔗使用-Wizard-创建项目"><a href="#🔗使用-Wizard-创建项目" class="headerlink" title="🔗使用 Wizard 创建项目"></a>🔗使用 Wizard 创建项目</h2><p>打开 Visual Studio 创建项目的时候能看到 AutoCAD CSharp plug-in，按照步骤创建即可。</p>
<p><img src="./wizard_1.png" alt=""></p>
<p>如下图所示，向导会询问两个路径，第一个填 ObjectARX 的 inc 目录，比如我填写的是： <strong>D:\ObjectARX_for_AutoCAD_2024_Win_64bit_dlm\inc</strong>。第二个路径填写的是 AutoCAD 的安装路径（包含 acad.exe）。</p>
<p><img src="./wizard_2.png" alt=""></p>
<p>创建好项目后直接开始调试，调试器会启动 AutoCAD，此时注意到 AutoCAD 本身也处于调试模式。在加载插件之前，设置的断点会提示无法命中，如下图。</p>
<p><img src="./wizard_3.png" alt=""></p>
<p>这是因为插件还没有被 AutoCAD 载入，在 AutoCAD 中新建一个图纸，然后执行 NETLOAD 命令，选择编译出来的 .dll 文件，就会注意到断点可以命中了。执行 MyCommand 指令，断点成功命中。</p>
<h2 id="🔗手动配置项目"><a href="#🔗手动配置项目" class="headerlink" title="🔗手动配置项目"></a>🔗手动配置项目</h2><p>首先创建一个 <strong>Class Library (.NET Framework)</strong> 项目，注意必须是带有 .NET Framework 的才可以。</p>
<p><img src="./manual_1.png" alt=""></p>
<h3 id="📖设置依赖引用"><a href="#📖设置依赖引用" class="headerlink" title="📖设置依赖引用"></a>📖设置依赖引用</h3><h4 id="方法-1：从-ObjectARX-的文件进行设置"><a href="#方法-1：从-ObjectARX-的文件进行设置" class="headerlink" title="方法 1：从 ObjectARX 的文件进行设置"></a>方法 1：从 ObjectARX 的文件进行设置</h4><p>如下图所示，右键项目中的 <strong>References</strong>（引用），选择 <strong>Add Reference</strong>（添加引用）。</p>
<blockquote>
<p>由于我的 Visual Studio 是英文，菜单选项的中文译名依赖回忆，因此可能不准确。</p>
</blockquote>
<p><img src="./manual_2.png" alt=""></p>
<p>展开 <strong>Browse</strong>（浏览）页面，然后点击 <strong>Browse</strong>（浏览）按钮进行选择。</p>
<p><img src="./manual_3.png" alt=""></p>
<p>导航到 ObjectARX 的 inc 目录，选择 “AcMgd.dll”、”AcCoreMgd.dll” 与 “AcDbMgd.dll” 三个 .dll 文件。</p>
<p><img src="./manual_4.png" alt=""></p>
<p>至此，依赖引用设置完成。</p>
<h4 id="方法-2-使用-NuGet"><a href="#方法-2-使用-NuGet" class="headerlink" title="方法 2: 使用 NuGet"></a>方法 2: 使用 NuGet</h4><p>如下图所示，右键项目中的 <strong>References</strong>（引用），选择 <strong>Manage NuGet Pacakages</strong>（管理 NuGet 包）。</p>
<p><img src="./manual_nuget_1.png" alt=""></p>
<p>在 <strong>Browse</strong> 页面中，搜索关键词 “AutoCAD”，在搜索结果中选择 “AutoCAD.NET”。注意右侧可以选择版本，请根据你的 AutoCAD 版本进行选择。比如图中所选择的版本 “24.1.51000”，从下方的 Description 中可以发现它对应的是 AutoCAD 2022。</p>
<p><img src="./manual_nuget_2.png" alt=""></p>
<p>选择正确的版本后，点击 <strong>Install</strong>，完成依赖配置。</p>
<h3 id="📖设置调试方法"><a href="#📖设置调试方法" class="headerlink" title="📖设置调试方法"></a>📖设置调试方法</h3><p>如图，点击 <strong>调试按钮</strong> 右边的 <strong>倒三角按钮</strong> 展开菜单，选择菜单中的 <strong>Debug Properties</strong> (调试属性)。</p>
<p><img src="./manual_debug_1.png" alt=""></p>
<p>如图，将 <strong>Start action</strong> 修改为 <strong>Start external program</strong>（启动外部程序），路径填写为 AutoCAD 安装目录下的 acad.exe 的路径。</p>
<p><img src="./manual_debug_2.png" alt=""></p>
<p>至此，调试方法设置完毕。</p>
<h3 id="📖创建基本代码"><a href="#📖创建基本代码" class="headerlink" title="📖创建基本代码"></a>📖创建基本代码</h3><p>这里的代码来自 Wizard 生成的项目，去掉了大部分注释（但其实那些注释还挺有用的，有助于了解这些代码在做什么）并略作修改。</p>
<p>创建一个 .cs 文件，命名为 “MyPlugin.cs”，内容如下：</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.ApplicationServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.DatabaseServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.EditorInput;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Geometry;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Runtime;</span><br><span class="line"><span class="keyword">using</span> System;</span><br><span class="line"></span><br><span class="line">[<span class="meta">assembly: ExtensionApplication(typeof(ClassLibrary.MyPlugin))</span>]</span><br><span class="line"><span class="keyword">namespace</span> <span class="title">ClassLibrary</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">public</span> <span class="keyword">class</span> <span class="title">MyPlugin</span> : <span class="title">IExtensionApplication</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">void</span> IExtensionApplication.Initialize()</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">// Initialize your plug-in application here</span></span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">void</span> IExtensionApplication.Terminate()</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">// Do plug-in application clean up here</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>注意把代码中的 “ClassLibrary” 修改为你自己项目的命名空间</p>
<p>再创建另一个 .cs 文件，命名为 MyCommand.cs”，内容如下：</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.ApplicationServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Colors;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.DatabaseServices;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.EditorInput;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Geometry;</span><br><span class="line"><span class="keyword">using</span> Autodesk.AutoCAD.Runtime;</span><br><span class="line"><span class="keyword">using</span> System;</span><br><span class="line"></span><br><span class="line">[<span class="meta">assembly: CommandClass(typeof(ClassLibrary.MyCommands))</span>]</span><br><span class="line"><span class="keyword">namespace</span> <span class="title">ClassLibrary</span></span><br><span class="line">&#123;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">public</span> <span class="keyword">class</span> <span class="title">MyCommands</span></span><br><span class="line">    &#123;</span><br><span class="line">        [<span class="meta">CommandMethod(<span class="string">&quot;MyCommand&quot;</span>, CommandFlags.Modal)</span>]</span><br><span class="line">        <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">MyCommand</span>() <span class="comment">// This method can have any name</span></span></span><br><span class="line">        &#123;</span><br><span class="line">            Document doc = Application.DocumentManager.MdiActiveDocument;</span><br><span class="line">            Editor ed;</span><br><span class="line">            <span class="keyword">if</span> (doc != <span class="literal">null</span>)</span><br><span class="line">            &#123;</span><br><span class="line">                ed = doc.Editor;</span><br><span class="line">                ed.WriteMessage(<span class="string">&quot;Hello, this is your first command.&quot;</span>);</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>至此，一个带有 “MyCommand” 命令的 AutoCAD 插件项目配置完毕。</p>
<h2 id="🔗最后"><a href="#🔗最后" class="headerlink" title="🔗最后"></a>🔗最后</h2><p>受限于写作经验，本文可能仍有不足，恳请批评指正。如果想转载本文，请在评论区或邮件联系我。</p>
</div><div class="article-licensing box"><div class="licensing-title"><p>基于ObjectARX .NET的AutoCAD二次开发：项目配置</p><p><a href="https://uint128.com/2023/07/11/基于ObjectARX-NET的AutoCAD二次开发快速入门/">https://uint128.com/2023/07/11/基于ObjectARX-NET的AutoCAD二次开发快速入门/</a></p></div><div class="licensing-meta level is-mobile"><div class="level-left"><div class="level-item is-narrow"><div><h6>作者</h6><p>uint128.com</p></div></div><div class="level-item is-narrow"><div><h6>发布于</h6><p>2023-07-11</p></div></div><div class="level-item is-narrow"><div><h6>更新于</h6><p>2023-07-12</p></div></div><div class="level-item is-narrow"><div><h6>许可协议</h6><p><a class="icons" rel="noopener" target="_blank" title="Creative Commons" href="https://creativecommons.org/"><i class="icon fab fa-creative-commons"></i></a><a class="icons" rel="noopener" target="_blank" title="Attribution" href="https://creativecommons.org/licenses/by/4.0/"><i class="icon fab fa-creative-commons-by"></i></a><a class="icons" rel="noopener" target="_blank" title="Noncommercial" href="https://creativecommons.org/licenses/by-nc/4.0/"><i class="icon fab fa-creative-commons-nc"></i></a></p></div></div></div></div></div><div class="article-tags is-size-7 mb-4"><span class="mr-2">#</span><a class="link-muted mr-2" rel="tag" href="/tags/AutoCAD/">AutoCAD</a><a class="link-muted mr-2" rel="tag" href="/tags/CSharp/">CSharp</a></div><!--!--></article></div><!--!--><div class="card"><nav class="post-navigation mt-4 level is-mobile card-content"><div class="level-end"><a class="article-nav-next level level-item link-muted" href="/2023/04/29/C-Concepts-%E7%9A%84%E4%B8%A4%E4%B8%AA%E6%8A%80%E5%B7%A7/"><span class="level-item">C++ Concepts 的两个技巧</span><i class="level-item fas fa-chevron-right"></i></a></div></nav></div><div class="card"><div class="card-content"><h3 class="title is-5">评论</h3><div id="comment-container"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1.7.2/dist/gitalk.css"><script src="https://cdn.jsdelivr.net/npm/gitalk@1.7.2/dist/gitalk.min.js"></script><script>var gitalk = new Gitalk({
            id: "3fa2d84873ae2aea9e27fba9a339106d",
            repo: "cyanray.github.io",
            owner: "cyanray",
            clientID: "53e3c578fcb7b7b1a4da",
            clientSecret: "74433ee77d6e13fd635b82add519e143ac791726",
            admin: ["cyanray"],
            createIssueManually: true,
            distractionFreeMode: false,
            perPage: 20,
            pagerDirection: "last",
            
            
            enableHotKey: true,
            language: "zh-CN",
        })
        gitalk.render('comment-container')</script></div></div></div><!--!--><div class="column column-right is-4-tablet is-4-desktop is-4-widescreen  order-3 is-sticky"><div class="card widget" id="toc" data-type="toc"><div class="card-content"><div class="menu"><h3 class="menu-label">目录</h3><ul class="menu-list"><li><a class="level is-mobile" href="#🔗开发目标"><span class="level-left"><span class="level-item">1</span><span class="level-item">🔗开发目标</span></span></a></li><li><a class="level is-mobile" href="#🔗前期准备"><span class="level-left"><span class="level-item">2</span><span class="level-item">🔗前期准备</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#📖安装-Visual-Studio"><span class="level-left"><span class="level-item">2.1</span><span class="level-item">📖安装 Visual Studio</span></span></a></li><li><a class="level is-mobile" href="#📖下载并解压-ObjectARX"><span class="level-left"><span class="level-item">2.2</span><span class="level-item">📖下载并解压 ObjectARX</span></span></a></li><li><a class="level is-mobile" href="#📖下载并安装-AutoCAD-DotNet-Wizard（可选）"><span class="level-left"><span class="level-item">2.3</span><span class="level-item">📖下载并安装 AutoCAD DotNet Wizard（可选）</span></span></a></li></ul></li><li><a class="level is-mobile" href="#🔗使用-Wizard-创建项目"><span class="level-left"><span class="level-item">3</span><span class="level-item">🔗使用 Wizard 创建项目</span></span></a></li><li><a class="level is-mobile" href="#🔗手动配置项目"><span class="level-left"><span class="level-item">4</span><span class="level-item">🔗手动配置项目</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#📖设置依赖引用"><span class="level-left"><span class="level-item">4.1</span><span class="level-item">📖设置依赖引用</span></span></a><ul class="menu-list"><li><a class="level is-mobile" href="#方法-1：从-ObjectARX-的文件进行设置"><span class="level-left"><span class="level-item">4.1.1</span><span class="level-item">方法 1：从 ObjectARX 的文件进行设置</span></span></a></li><li><a class="level is-mobile" href="#方法-2-使用-NuGet"><span class="level-left"><span class="level-item">4.1.2</span><span class="level-item">方法 2: 使用 NuGet</span></span></a></li></ul></li><li><a class="level is-mobile" href="#📖设置调试方法"><span class="level-left"><span class="level-item">4.2</span><span class="level-item">📖设置调试方法</span></span></a></li><li><a class="level is-mobile" href="#📖创建基本代码"><span class="level-left"><span class="level-item">4.3</span><span class="level-item">📖创建基本代码</span></span></a></li></ul></li><li><a class="level is-mobile" href="#🔗最后"><span class="level-left"><span class="level-item">5</span><span class="level-item">🔗最后</span></span></a></li></ul></div></div><style>#toc .menu-list > li > a.is-active + .menu-list { display: block; }#toc .menu-list > li > a + .menu-list { display: none; }</style><script src="/js/toc.js" defer></script></div><div class="card widget" data-type="recent-posts"><div class="card-content"><h3 class="menu-label">最新文章</h3><article class="media"><div class="media-content"><p class="date"><time dateTime="2023-07-11T06:30:05.000Z">2023-07-11</time></p><p class="title"><a href="/2023/07/11/%E5%9F%BA%E4%BA%8EObjectARX-NET%E7%9A%84AutoCAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/">基于ObjectARX .NET的AutoCAD二次开发：项目配置</a></p></div></article><article class="media"><div class="media-content"><p class="date"><time dateTime="2023-04-29T09:02:24.000Z">2023-04-29</time></p><p class="title"><a href="/2023/04/29/C-Concepts-%E7%9A%84%E4%B8%A4%E4%B8%AA%E6%8A%80%E5%B7%A7/">C++ Concepts 的两个技巧</a></p></div></article><article class="media"><div class="media-content"><p class="date"><time dateTime="2023-03-06T15:23:32.000Z">2023-03-06</time></p><p class="title"><a href="/2023/03/06/Modern-CMake-%E5%AE%9E%E8%B7%B5/">Modern CMake 实践</a></p></div></article><article class="media"><div class="media-content"><p class="date"><time dateTime="2023-01-07T18:40:09.000Z">2023-01-08</time></p><p class="title"><a href="/2023/01/08/%E7%89%9B%E9%A1%BF%E6%8F%92%E5%80%BC%E6%B3%95%E7%9A%84-Matlab-%E5%AE%9E%E7%8E%B0/">牛顿插值法的 Matlab 实现</a></p></div></article><article class="media"><div class="media-content"><p class="date"><time dateTime="2023-01-07T18:38:42.000Z">2023-01-08</time></p><p class="title"><a href="/2023/01/08/%E5%A4%9A%E5%85%83%E7%89%9B%E9%A1%BF%E8%BF%AD%E4%BB%A3%E6%B3%95%E7%9A%84-Matlab-%E5%AE%9E%E7%8E%B0/">多元牛顿迭代法的 Matlab 实现</a></p></div></article></div></div><div class="card widget" data-type="links"><div class="card-content"><div class="menu"><h3 class="menu-label">链接</h3><ul class="menu-list"><li><a class="level is-mobile" href="https://yuanxingxing-yxx.github.io/" target="_blank" rel="noopener"><span class="level-left"><span class="level-item">星星的博客</span></span><span class="level-right"><span class="level-item tag">yuanxingxing-yxx.github.io</span></span></a></li><li><a class="level is-mobile" href="http://quosimodo.cn/" target="_blank" rel="noopener"><span class="level-left"><span class="level-item">卡西莫多の礼物</span></span><span class="level-right"><span class="level-item tag">quosimodo.cn</span></span></a></li><li><a class="level is-mobile" href="https://blog.icepie.net/" target="_blank" rel="noopener"><span class="level-left"><span class="level-item">icepie&#039;s blog</span></span><span class="level-right"><span class="level-item tag">blog.icepie.net</span></span></a></li><li><a class="level is-mobile" href="https://www.cnblogs.com/sherlson" target="_blank" rel="noopener"><span class="level-left"><span class="level-item">sherlson&#039;s blog</span></span><span class="level-right"><span class="level-item tag">www.cnblogs.com</span></span></a></li><li><a class="level is-mobile" href="http://blog.devilwst.top/" target="_blank" rel="noopener"><span class="level-left"><span class="level-item">小生的技术成长路线</span></span><span class="level-right"><span class="level-item tag">blog.devilwst.top</span></span></a></li><li><a class="level is-mobile" href="http://nico233.cn/" target="_blank" rel="noopener"><span class="level-left"><span class="level-item">nico233&#039;s blog</span></span><span class="level-right"><span class="level-item tag">nico233.cn</span></span></a></li></ul></div></div></div></div></div></div></section><footer class="footer"><div class="container"><div class="level"><div class="level-start"><a class="footer-logo is-block mb-2" href="/">uint128&#039;s Blog</a><p class="is-size-7"><span>&copy; 2023 uint128.com</span>  Powered by <a href="https://hexo.io/" target="_blank" rel="noopener">Hexo</a> &amp; <a href="https://github.com/ppoffice/hexo-theme-icarus" target="_blank" rel="noopener">Icarus</a></p></div><div class="level-end"><div class="field has-addons"><p class="control"><a class="button is-transparent is-large" target="_blank" rel="noopener" title="Creative Commons" href="https://creativecommons.org/"><i class="fab fa-creative-commons"></i></a></p><p class="control"><a class="button is-transparent is-large" target="_blank" rel="noopener" title="Attribution 4.0 International" href="https://creativecommons.org/licenses/by/4.0/"><i class="fab fa-creative-commons-by"></i></a></p></div></div></div></div></footer><script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/min/moment-with-locales.min.js"></script><script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.min.js" async></script><script>moment.locale("zh-CN");</script><script>var IcarusThemeSettings = {
            article: {
                highlight: {
                    clipboard: true,
                    fold: 'unfolded'
                }
            }
        };</script><script src="/js/column.js"></script><script src="/js/animation.js"></script><a id="back-to-top" title="回到顶端" href="javascript:;"><i class="fas fa-chevron-up"></i></a><script src="/js/back_to_top.js" defer></script><!--!--><!--!--><!--!--><script src="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.js" defer></script><script>window.addEventListener("load", () => {
      window.cookieconsent.initialise({
        type: "info",
        theme: "edgeless",
        static: false,
        position: "bottom-left",
        content: {
          message: "此网站使用Cookie来改善您的体验。",
          dismiss: "知道了！",
          allow: "允许使用Cookie",
          deny: "拒绝",
          link: "了解更多",
          policy: "Cookie政策",
          href: "https://www.cookiesandyou.com/",
        },
        palette: {
          popup: {
            background: "#edeff5",
            text: "#838391"
          },
          button: {
            background: "#4b81e8"
          },
        },
      });
    });</script><script src="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/js/lightgallery.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js" defer></script><script>window.addEventListener("load", () => {
            if (typeof $.fn.lightGallery === 'function') {
                $('.article').lightGallery({ selector: '.gallery-item' });
            }
            if (typeof $.fn.justifiedGallery === 'function') {
                if ($('.justified-gallery > p > .gallery-item').length) {
                    $('.justified-gallery > p > .gallery-item').unwrap();
                }
                $('.justified-gallery').justifiedGallery();
            }
        });</script><!--!--><!--!--><script type="text/x-mathjax-config">MathJax.Hub.Config({
            'HTML-CSS': {
                matchFontHeight: false
            },
            SVG: {
                matchFontHeight: false
            },
            CommonHTML: {
                matchFontHeight: false
            },
            tex2jax: {
                inlineMath: [
                    ['$','$'],
                    ['\\(','\\)']
                ]
            }
        });</script><script src="https://cdn.jsdelivr.net/npm/mathjax@2.7.9/unpacked/MathJax.js?config=TeX-MML-AM_CHTML" defer></script><!--!--><!--!--><!--!--><script src="/js/main.js" defer></script><div class="searchbox"><div class="searchbox-container"><div class="searchbox-header"><div class="searchbox-input-container"><input class="searchbox-input" type="text" placeholder="想要查找什么..."></div><a class="searchbox-close" href="javascript:;">×</a></div><div class="searchbox-body"></div></div></div><script src="/js/insight.js" defer></script><script>document.addEventListener('DOMContentLoaded', function () {
            loadInsight({"contentUrl":"/content.json"}, {"hint":"想要查找什么...","untitled":"(无标题)","posts":"文章","pages":"页面","categories":"分类","tags":"标签"});
        });</script><script type="text/javascript" src="/js/imaegoo/universe.js"></script><!-- hexo-inject:begin --><!-- hexo-inject:end --></body></html>